version: 1.0.{build}
skip_tags: false
configuration: Release
init:
- ps: >-
    $parsedReleaseBuildVersion = $env:APPVEYOR_REPO_TAG_NAME -Match "(\d+.\d+.\d+(.\d+)?)"

    If($env:appveyor_repo_tag -AND $parsedReleaseBuildVersion) {
      $env:BuildVersion = $matches[0]
      $env:IsGithubRelease = $TRUE
    } else {
      $env:BuildVersion = $env:appveyor_build_version
      $env:IsGithubRelease = ""
    }

    Write-Host "Build Version: " $env:BuildVersion

    Write-Host "appveyor_build_version Variable: " $env:appveyor_build_version
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(BuildVersion)
  assembly_file_version: $(BuildVersion)
  assembly_informational_version: $(BuildVersion)
nuget:
  account_feed: true
  project_feed: true
before_build:
- nuget restore ColorCat.sln
build:
  project: ColorCat.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cpack ColorCat\Chocolatey\package.nuspec --version %BuildVersion%
artifacts:
- path: ColorCat\bin\$(configuration)
  name: bin
- path: '*.nupkg'
  name: package
deploy:
- provider: GitHub
  auth_token:
    secure: zBj7kH3ngT1v5Bh9HfJFLO44yBrwJ55KhsWWv6zgkSrrBrIvkJq/0h/unEThGYIg
  artifact: 
  prerelease: false
  on:
    branch: master
    IsGithubRelease: true
- provider: NuGet
  server: https://chocolatey.org/
  api_key:
    secure: 2Uqi8iUyKSHUakCSDeJb+qeXjn8i87F2U9RRmQIsqz4HOSycTjhat5AxHNs0yJ4g
  artifact: package
  on:
    branch: master
    IsGithubRelease: true
